<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($block->getTotal()->getValue()): ?>
    <tr class="rewardpoints">
        <th colspan="<?php /* @escapeNotVerified */ echo $block->getColspan(); ?>" style="<?php /* @escapeNotVerified */ echo $block->getTotal()->getStyle() ?>" class="mark" scope="row">
            <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?><strong><?php endif; ?>
                <?php $_title = __('Remove'); ?>
                <?php $_url = $block->getRemoveRewardTotalUrl(); ?>
                <a href="<?php /* @escapeNotVerified */ echo $_url; ?>" title="<?php /* @escapeNotVerified */ echo $_title; ?>" class="action delete"><span><?php /* @escapeNotVerified */ echo $_title; ?></span></a>
                <?php /* @escapeNotVerified */ echo $block->getTotal()->getTitle(); ?>
            <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?></strong><?php endif; ?>
        </th>
        <td style="<?php /* @escapeNotVerified */ echo $block->getTotal()->getStyle() ?>" class="amount"
            data-th="<?php echo $block->escapeHtml($block->getTotal()->getTitle()); ?>">
            <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?><strong><?php endif; ?>
                <?php /* @escapeNotVerified */ echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($block->getTotal()->getValue()) ?>
            <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?></strong><?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
