<?php
/** @var \TIG\Buckaroo\Block\Adminhtml\Config\Support\SupportTab $this */
?>
<div id="supporttab" class="tig-buckaroo-supporttab" data-mage-init='{"buckarooConfig": true}'>

    <?php // section 1 ?>
    <div id="section">
        <div class="collapse-title" data-role="title">
            <h3 data-role="trigger" ><?php echo $block->escapeHtml(__('Quick reference guide'));?></h3>
        </div>
        <div class="collapse-content" data-role="content" style="display:none;">
            <ol>
                <li><strong><?php echo $block->escapeHtml(__('Log in to the '));?> <a target="_blank" href="https://payment.buckaroo.nl/"><?php echo $block->escapeHtml(__('Buckaroo Payment Plaza'));?></a> <?php echo $block->escapeHtml(__(' to collect the following security settings:'));?></strong>
                    <ol>
                        <li><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet, id lacinia sodales, massa at mattis vestibulum'));?></li>
                        <li><?php echo $block->escapeHtml(__('Metus est odio, proin donec, dui orci quis pede vel nec'));?></li>
                        <li><?php echo $block->escapeHtml(__('Dolor parturient id laoreet. Ipsum in et elit. Augue enim non vehicula posuere nulla, at non'));?></li>
                        <li><?php echo $block->escapeHtml(__('Nam laboriosam massa ac, libero nostra netus tellus. Lacinia egestas dapibus sapien parturient erat mauris'));?></li>
                        <li><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet, id lacinia sodales, massa at mattis vestibulum'));?></li>
                    </ol>
                </li>
                <li><strong><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet, id lacinia sodales, massa at mattis vestibulum'));?></strong>
                    <ol>
                        <li><?php echo $block->escapeHtml(__('Dolor parturient id laoreet. Ipsum in et elit. Augue enim non vehicula posuere nulla, at non'));?></li>
                        <li><?php echo $block->escapeHtml(__('Nam laboriosam massa ac, libero nostra netus tellus. Lacinia egestas dapibus sapien parturient erat mauris'));?></li>
                    </ol>
                </li>
                <li><strong><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet, id lacinia sodales, massa at mattis vestibulum'));?></strong>
                    <ol>
                        <li><?php echo $block->escapeHtml(__('Nam laboriosam massa ac, libero nostra netus tellus. Lacinia egestas dapibus sapien parturient erat mauris'));?></li>
                        <li><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet, id lacinia sodales, massa at mattis vestibulum'));?></li>
                        <li><?php echo $block->escapeHtml(__('Metus est odio, proin donec, dui orci quis pede vel nec'));?></li>
                    </ol>
                </li>
                <li><strong><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet, id lacinia sodales, massa at mattis vestibulum'));?></strong>
                    <ol>
                        <li><?php echo $block->escapeHtml(__('Metus est odio, proin donec, dui orci quis pede vel nec'));?></li>
                        <li><?php echo $block->escapeHtml(__('Nam laboriosam massa ac, libero nostra netus tellus. Lacinia egestas dapibus sapien parturient erat mauris'));?></li>
                        <li><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet, id lacinia sodales, massa at mattis vestibulum'));?></li>
                    </ol>
                </li>
                <li><strong><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet, id lacinia sodales, massa at mattis vestibulum'));?></strong>
                    <ol>
                        <li><?php echo $block->escapeHtml(__('Metus est odio, proin donec, dui orci quis pede vel nec'));?></li>
                        <li><?php echo $block->escapeHtml(__('Dolor parturient id laoreet. Ipsum in et elit. Augue enim non vehicula posuere nulla, at non'));?></li>
                        <li><?php echo $block->escapeHtml(__('Nam laboriosam massa ac, libero nostra netus tellus. Lacinia egestas dapibus sapien parturient erat mauris'));?></li>
                        <li><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet, id lacinia sodales, massa at mattis vestibulum'));?></li>
                    </ol>
                </li>
            </ol>
        </div>
    </div>

    <?php // section 2 ?>
    <div id="section">
        <div class="collapse-title" data-role="title">
            <h3 data-role="trigger"><?php echo $block->escapeHtml(__('Legend'));?></h3>
        </div>
        <div class="collapse-content" data-role="content" style="display:none;">
            <ul id="legend">
                <li class="disabled">
                    <span class="img"></span>
                    <span class="text"><?php echo $block->escapeHtml(__('Payment method'));?> : </span>
                    <span class="status"><?php echo $block->escapeHtml(__('Disabled'));?></span>
                </li>
                <li class="test">
                    <span class="img"></span>
                    <span class="text"><?php echo $block->escapeHtml(__('Payment method'));?> : </span>
                    <span class="status"><?php echo $block->escapeHtml(__('Test Modus'));?></span>
                </li>
                <li class="live">
                    <span class="img"></span>
                    <span class="text"><?php echo $block->escapeHtml(__('Payment method'));?> : </span>
                    <span class="status"><?php echo $block->escapeHtml(__('Live Modus'));?></span>
                </li>
                <!--                <li class="advanced"><span></span>--><?php //echo $block->escapeHtml(__('Advanced Configuration'));?><!--</li>-->
            </ul>
        </div>
    </div>

    <?php // section 3 ?>
    <div id="section">
        <div class="collapse-title" data-role="title">
            <h3 data-role="trigger"><?php echo $block->escapeHtml(__('Magento &amp; 3rd party version compatibility'));?></h3>
        </div>
        <div class="collapse-content" data-role="content" style="display:none;">
            <ul class="version-compatibility">
                <li>
                    <span class="text"><?php echo $block->escapeHtml(__('Magento Community Edition version'));?> :</span>
                    <span class="version"> 2.0 </span>
                </li>
                <li>
                    <span class="text"><?php echo $block->escapeHtml(__('Magento Enterprise Edition version'));?> :</span>
                    <span class="version"> 2.0 </span>
                </li>
            </ul>
            <ul class="version-compatibility">
                <li>
                    <span class="text"><?php echo $block->escapeHtml(__('Lorem Ipsum'));?> :</span>
                    <span class="version"> 2.0 </span>
                </li>
            </ul>
        </div>
    </div>

    <?php // section 4 ?>
    <div id="section">
        <div class="collapse-title" data-role="title">
            <h3 data-role="trigger"><?php echo $block->escapeHtml(__('Support'));?></h3>
        </div>
        <div class="collapse-content support-buck-tig" data-role="content" style="display:none;">
            <ul>
                <p><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet, id lacinia sodales, massa at mattis vestibulum'));?></p>
<!--                <p>--><?php //echo $block->escapeHtml(__('This extension is developed by TIG, commissioned by Buckaroo.'));?><!--</p>-->
                <h4><?php echo $block->escapeHtml(__('Module basic configuration and account information'));?></h4>
                <p><?php echo $block->escapeHtml(__('Nam laboriosam massa ac, libero nostra netus tellus. Lacinia egestas dapibus sapien parturient erat mauris:'));?></p>
            </ul>
            <ul>
                <li class="buckaroo_logo" ><a href="http://www.buckaroo.nl" target="_blank"><img src="<?php echo $this->getViewFileUrl('TIG_Buckaroo::images/buckaroo_config_logo.png'); ?> " alt="" /></a></li>
                <li class="first"><?php echo $block->escapeHtml(__('Buckaroo Payment Plaza:'));?></li>
                <li class="last"><a target="_blank" href="https://payment.buckaroo.nl/">payment.buckaroo.nl</a></li>
            </ul>
            <ul>
                <li class="first"><?php echo $block->escapeHtml(__('Phone:'));?></li>
                <li class="last">+31(0)30-711 50 50</li>
            </ul>
            <ul>
                <li class="first"><?php echo $block->escapeHtml(__('E-mail:'));?></li>
                <li class="last"><a href="mailto:support@buckaroo.nl">support@buckaroo.nl</a></li>
            </ul>
            <ul>
                <h4><?php echo $block->escapeHtml(__('Extension support and advanced configuration'));?></h4>

                <li class="tig_logo"><a href="http://www.tig.nl" target="_blank"><img src="<?php echo $this->getViewFileUrl('TIG_Buckaroo::images/logo_tig.png'); ?>" alt="" /></a></li>
                <li class="first"><?php echo $block->escapeHtml(__('Online documentation and FAQ:'));?></li>
                <li class="last"><a target="_blank" href="http://kb.tig.nl/">kb.tig.nl</a></li>
            </ul>
            <ul>
                <li class="first"><?php echo $block->escapeHtml(__('Request support:'));?></li>
                <li class="last"><a target="_blank" href="http://kb.tig.nl/ticket/form/new">kb.tig.nl/ticket/form/new</a></li>
            </ul>
            <ul>
                <li class="first"><?php echo $block->escapeHtml(__('Misc. questions by email:'));?></li>
                <li class="last"><a href="mailto:servicedesk@tig.nl">servicedesk@tig.nl</a></li>
            </ul>
        </div>
    </div>

    <?php // section 5 ?>
    <div id="section">
        <div class="collapse-title" data-role="title">
            <h3 data-role="trigger"><?php echo $block->escapeHtml(__('Documentation'));?></h3>
        </div>
        <div class="collapse-content" data-role="content" style="display:none;">
            <ul>
                <p><?php echo $block->escapeHtml(__('A list of documents regarding the module.'));?></p>
                <li><a class="pdf" target="_blank" href="http://kb.tig.nl/topic/22098908" title="<?php echo $block->escapeHtml(__('Download a PDF format of the manual. Currently the manual is only available in Dutch.'));?>"><?php echo $block->escapeHtml(__('Installation Manual Buckaroo.pdf (NL)'));?></a></li>
                <li><a target="_blank" href="http://kb.tig.nl/topic/23902302" title="<?php echo $block->escapeHtml(__('View the complete changelog of the module. Currently the changelog is only available in Dutch.'));?>"><?php echo $block->escapeHtml(__('Full Changelog'));?></a></li>
            </ul>
        </div>
    </div>

</div>
