<?php
/** @var \TIG\Buckaroo\Block\Adminhtml\Config\Support\SupportTab $this */
?>
<div id="supporttab" class="tig-buckaroo-supporttab" data-mage-init='{"buckarooConfig": true}'>


    <div id="block">
        <div class="block-legend">
            <h3 ><?php echo $block->escapeHtml(__('Legend'));?></h3>
            <div>
                <ul id="legend">
                    <li class="disabled">
                        <span class="img"></span>
                        <span class="text"><?php echo $block->escapeHtml(__('Payment method'));?>: </span>
                        <span class="status"><?php echo $block->escapeHtml(__('Disabled'));?></span>
                    </li>
                    <li class="test">
                        <span class="img"></span>
                        <span class="text"><?php echo $block->escapeHtml(__('Payment method'));?>: </span>
                        <span class="status"><?php echo $block->escapeHtml(__('Test Mode'));?></span>
                    </li>
                    <li class="live">
                        <span class="img"></span>
                        <span class="text"><?php echo $block->escapeHtml(__('Payment method'));?>: </span>
                        <span class="status"><?php echo $block->escapeHtml(__('Live Mode'));?></span>
                    </li>
                </ul>
            </div>
        </div>

        <div class="block-version">
            <h3 ><?php echo $block->escapeHtml(__('Magento version compatibility'));?></h3>
            <div>
                <ul class="version-compatibility">
                    <li>
                        <span class="text">
                            <?php echo $block->escapeHtml(__('Magento Enterprise Edition version'));?>:
                        </span>
                        <span class="version"> 2.0.8 - 2.0.16, 2.1.0 - 2.1.9 </span>
                    </li>
                    <li>
                        <span class="text">
                            <?php echo $block->escapeHtml(__('Magento Community Edition version'));?>:
                        </span>
                        <span class="version"> 2.0.8 - 2.0.16, 2.1.0 - 2.1.9 </span>
                    </li>
                    <li>
                        <span class="text"><?php echo $block->escapeHtml(__('Buckaroo version'));?>:</span>
                        <span class="version"><?php echo $block->escapeHtml($this->getVersionNumber()); ?></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div id="section">
        <div class="collapse-title" data-role="title">
            <h3 data-role="trigger"><?php echo $block->escapeHtml(__('Support'));?></h3>
        </div>
        <div class="collapse-content support-buck-tig" data-role="content" style="display:none;">
            <ul>
                <p>
                    <?php echo $block->escapeHtml(
                        __('This extension is developed by TIG, commissioned by Buckaroo.')
                    );?>
                </p>
                <h4><?php echo $block->escapeHtml(__('Extension basic configuration and account information'));?></h4>
                <p>
                    <?php echo $block->escapeHtml(__(
                        'Before contacting Buckaroo technical support, please retrieve your (Merchant) key, ' .
                        'Secret key, certificate and certificate thumbprint.'
                    ));?>
                </p>
            </ul>
            <ul>
                <li class="buckaroo_logo" >
                    <a href="https://<?php echo $block->escapeHtml(__('www.buckaroo-payments.com'));?>"
                       target="_blank">
                        <img src="<?php echo $this->getViewFileUrl(
                            'TIG_Buckaroo::images/buckaroo_config_logo_black.png'
                        ); ?>"
                             alt="" />
                    </a>
                </li>
                <li class="first"><?php echo $block->escapeHtml(__('Buckaroo Payment Plaza:'));?></li>
                <li class="last"><a target="_blank" href="https://plaza.buckaroo.nl/">plaza.buckaroo.nl</a></li>
            </ul>
            <ul>
                <li class="first"><?php echo $block->escapeHtml(__('Phone:'));?></li>
                <li class="last">+31(0)30-711 50 50</li>
            </ul>
            <ul>
                <li class="first"><?php echo $block->escapeHtml(__('E-mail:'));?></li>
                <li class="last"><a href="mailto:support@buckaroo.nl">support@buckaroo.nl</a></li>
            </ul>
            <ul>
                <li class="first"><?php echo $block->escapeHtml(__('Website:'));?></li>
                <li class="last">
                    <a href="https://<?php echo $block->escapeHtml(__('www.buckaroo-payments.com'));?>"
                       target="_blank">
                        <?php echo $block->escapeHtml(__('www.buckaroo-payments.com'));?>
                    </a>
                </li>
            </ul>


            <ul>
                <h4><?php echo $block->escapeHtml(__('Extension support and advanced configuration'));?></h4>

                <li class="tig_logo">
                    <a href="http://www.tig.nl/" target="_blank">
                        <img src="<?php echo $this->getViewFileUrl('TIG_Buckaroo::images/logo_tig.png'); ?>" alt="" />
                    </a>
                </li>
                <li class="first"><?php echo $block->escapeHtml(__('Online documentation and FAQ:'));?></li>
                <li class="last">
                    <a target="_blank" href="http://servicedesk.tig.nl/hc/nl/sections/203522128/">
                        <?php echo $block->escapeHtml(__('TIG Knowledge Base'));?>
                    </a>
                </li>
            </ul>
            <ul>
                <li class="first"><?php echo $block->escapeHtml(__('Support question:'));?></li>
                <li class="last">
                    <a target="_blank" href="http://servicedesk.tig.nl/hc/nl/requests/new">
                        <?php echo $block->escapeHtml(__('TIG Request Form'));?>
                    </a>
                </li>
            </ul>
            <ul>
                <li class="first"><?php echo $block->escapeHtml(__('Support by email:'));?></li>
                <li class="last"><a href="mailto:servicedesk@tig.nl">servicedesk@tig.nl</a></li>
            </ul>
            <ul>
                <li class="first"><?php echo $block->escapeHtml(__('Website'));?></li>
                <li class="last"><a href="https://www.tig.nl/" target="_blank">www.tig.nl</a></li>
            </ul>
        </div>
    </div>

    <div id="section">
        <div class="collapse-title" data-role="title">
            <h3 data-role="trigger"><?php echo $block->escapeHtml(__('Documentation'));?></h3>
        </div>
        <div class="collapse-content" data-role="content" style="display:none;">
            <ul>
                <p><?php echo $block->escapeHtml(__('A list of documents regarding the extension.'));?></p>
                <li>
                    <a class="pdf" target="_blank"
                       href="http://<?php echo $block->escapeHtml(
                           __("servicedesk.tig.nl/hc/nl/articles/218518187")
                       );?>"
                       title="<?php echo $block->escapeHtml(
                           __('Download a PDF format of the manual. Currently the manual is only available in English.')
                       );?>">
                        <?php echo $block->escapeHtml(__('Installation and Configuration Manual Buckaroo.pdf'));?>
                        <img class="external_link"
                             src="<?php echo $this->getViewFileUrl('TIG_Buckaroo::images/external_link_32.png')?>"
                             alt="<?php echo $block->escapeHtml(
                                 __('Installation and Configuration Manual Buckaroo.pdf')
                             );?>"
                             width="16" height="16"/>
                    </a>
                </li>
                <li>
                    <a target="_blank"
                       href="http://<?php echo $block->escapeHtml(
                           __("servicedesk.tig.nl/hc/nl/articles/218003338")
                       );?>"
                       title="<?php echo $block->escapeHtml(
                           __('View the complete release notes of the extension. Currently the release notes is only available in English.')
                       );?>">
                        <?php echo $block->escapeHtml(__('Full Release Notes'));?>
                        <img class="external_link"
                             src="<?php echo $this->getViewFileUrl('TIG_Buckaroo::images/external_link_32.png')?>"
                             alt="<?php echo $block->escapeHtml(__('Full Release Notes'));?>" width="16" height="16"/>
                    </a>
                </li>
            </ul>
        </div>
    </div>

</div>
